### ISSUE TITLE
Увеличить дефолтный лимит на memlock

### ISSUE THREAD

**Issue by ei-grad** [sat2707/hlcupdocs#67]
Есть подозрение что начальные пики времени ответа вызываются отправкой страниц памяти приложения в swap. Кто-то с этим успешно борется "разогревом", но правильный способ - использование вызова mlockall.

https://docs.docker.com/compose/compose-file/#ulimits

Нужно добавить в секцию ulimits блок memlock:

```
ulimits:
  memlock:
    soft: 4294967296
    hard: 4294967296
```
